name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo "Hello, ${NAME}"
    - name: Run a multi-line script
      run: echo  "Hello, ${{ secrets.SECRET_VALUE }}"
